import { execSync } from "node:child_process";
import { writeFileSync, readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const rootDir = path.resolve(__dirname, "..");
const targetFile = path.join(rootDir, "version.ts");

function resolveVersion() {
  // 1. Check if exact tag on current commit
  try {
    const tag = execSync("git describe --tags --exact-match 2>/dev/null", {
      cwd: rootDir,
      encoding: "utf8",
    }).trim();
    if (tag) return tag;
  } catch {}

  // 2. Check git short hash
  try {
    const hash = execSync("git rev-parse --short HEAD 2>/dev/null", {
      cwd: rootDir,
      encoding: "utf8",
    }).trim();
    if (hash) return `beta-${hash}`;
  } catch {}

  // 3. Fallback to package.json
  try {
    const pkg = JSON.parse(readFileSync(path.join(rootDir, "package.json"), "utf8"));
    if (pkg.version) return `v${pkg.version}`;
  } catch {}

  return "0.0.0-dev";
}

const version = resolveVersion();
const content = `// Auto-generated by scripts/version.mjs during build. Do not edit directly.\nexport const PLUGIN_VERSION = "${version}";\n`;

let existing = "";
if (existsSync(targetFile)) {
  existing = readFileSync(targetFile, "utf8");
}

if (existing !== content) {
  writeFileSync(targetFile, content, "utf8");
  console.log(`[build] Stamped PLUGIN_VERSION = "${version}" in version.ts`);
} else {
  console.log(`[build] PLUGIN_VERSION is up to date: "${version}"`);
}
